[project]
name = "datamarket-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Daniel", email = "collazosvalerodanielfelipe@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.142.2",
    "psycopg2>=2.9.13",
]

[project.scripts]
datamarket-project = "datamarket_project:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
